<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="MacBook-Pro" name="com.app.tests.HomePageTests" tests="6" failures="1" timestamp="22 Jan 2019 07:39:59 GMT" time="15.125" errors="0">
  <testcase name="verifyNavTitles" time="0.124" classname="com.app.tests.HomePageTests">
    <failure type="java.lang.AssertionError" message="Failed: T-Shirts page is not displayed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Failed: T-Shirts page is not displayed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at com.app.tests.HomePageTests.verifyNavTitles(HomePageTests.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyNavTitles -->
  <testcase name="verifyNewsletterInputAlert" time="4.726" classname="com.app.tests.HomePageTests"/>
  <testcase name="verifyMenuNavigation" time="9.942" classname="com.app.tests.HomePageTests"/>
  <testcase name="verifyLogo" time="0.057" classname="com.app.tests.HomePageTests"/>
  <testcase name="verifyNavTitles" time="0.151" classname="com.app.tests.HomePageTests">
    <skipped/>
  </testcase> <!-- verifyNavTitles -->
  <testcase name="verifyNavTitles" time="0.125" classname="com.app.tests.HomePageTests">
    <skipped/>
  </testcase> <!-- verifyNavTitles -->
</testsuite> <!-- com.app.tests.HomePageTests -->
